# Generated by Django 5.0.6 on 2024-06-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_banner_cor_alter_itemestoque_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
